import { jsPDF } from 'jspdf';

export const generatePdfReport = (event) => {
  if (!event) return;
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  // 1. Header Banner
  doc.setFillColor(79, 70, 229); // Indigo 600
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('ROTARACT IMPACT REPORT', 20, 25);
  
  // 2. Event Basics
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(20);
  doc.text(event.name || 'Event Name', 20, 55);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  
  const dateStr = event.date ? new Date(event.date).toLocaleDateString() : 'N/A';
  const categoryStr = event.category || 'N/A';
  const locationStr = event.location || 'N/A';
  const clubStr = event.author?.club || 'Unknown Club';
  
  doc.text(`Date: ${dateStr}  |  Category: ${categoryStr}`, 20, 65);
  doc.text(`Location: ${locationStr}  |  Host: ${clubStr}`, 20, 72);
  
  // Separator
  doc.setDrawColor(220, 220, 220);
  doc.line(20, 78, pageWidth - 20, 78);

  // 3. Impact Metrics (Boxes)
  const vols = event.volunteers || 0;
  const benfs = event.beneficiaries || 0;
  const aiScore = event.impactAnalysis && event.impactAnalysis.impactScore ? event.impactAnalysis.impactScore : 'N/A';
  
  doc.setFillColor(248, 250, 252);
  doc.rect(20, 85, 50, 20, 'F');
  doc.rect(75, 85, 50, 20, 'F');
  doc.rect(130, 85, 60, 20, 'F');
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Volunteers', 45, 93, { align: 'center' });
  doc.text('Beneficiaries', 100, 93, { align: 'center' });
  doc.text('AI Impact Score', 160, 93, { align: 'center' });
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(`${vols}`, 45, 101, { align: 'center' });
  doc.text(`${benfs}`, 100, 101, { align: 'center' });
  
  doc.setTextColor(79, 70, 229);
  doc.text(`${aiScore}`, 160, 101, { align: 'center' });
  
  // 4. Description / AI Report
  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59);
  doc.text('Executive Summary', 20, 120);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(70, 70, 70);
  
  // If AI report exists, use it. Otherwise use normal description.
  const content = event.aiReport || event.description || 'No description provided.';
  
  // Very basic regex to strip markdown formatting (bold, italics) if Gemini returned any
  const cleanContent = content.replace(/\*\*/g, '').replace(/\*/g, '').replace(/#/g, '');
  
  const splitContent = doc.splitTextToSize(cleanContent, pageWidth - 40);
  
  let cursorY = 130;
  for (let i = 0; i < splitContent.length; i++) {
    if (cursorY > pageHeight - 20) {
      doc.addPage();
      cursorY = 20;
    }
    doc.text(splitContent[i], 20, cursorY);
    cursorY += 6;
  }
  
  // 5. Footer
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by Rotaract Smart Reporting System • Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  doc.save(`${(event.name || 'Event').replace(/\s+/g, '_')}_Impact_Report.pdf`);
};
